### PR TITLE
Release Drafter: Make the configuration compatible with JCasC plugin

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This change merges configurations we have in two repos.

CC @jenkinsci/configuration-as-code-plugin-developers

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
If https://github.com/toolmantim/release-drafter/issues/218 is implemented by somebody (me?), it will look much prettier

**Comment by oleg-nenashev** [comment]
I will land it so that I get the `bug` configuration I need for other changelogs.
Will be happy to address all comments in follow-ups

**Comment by casz** [comment]
Well @oleg-nenashev actually be prepared to change those :laughing:

**Comment by oleg-nenashev** [comment]
Yeah. There is a non-zero chance that it does not work at all after the merge

**Comment by casz** [comment]
I was referring to: https://github.com/toolmantim/release-drafter/pull/219 :rofl:

**Pull request merged**
