### PR TITLE
Expand/contract version details in bug report template

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Use expandable details section in bug report template

- Use an expandable details section for version info report
- Use numbered list for repro steps

See https://github.com/jenkinsci/gitlab-branch-source-plugin/issues/138 for an example of the technique.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Please consider this an experiment for discussion.  I hope it will improve the content of bug reports but I am concerned that the added complexity of the expandable details section may actually reduce the quality of bug reports.  Many bug report submitters already ignore comments.  I believe this change improves the experience for everyone that reads the bug reports, but it may not help those who submit the bug reports.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
oops

**Comment by NotMyFault** [comment]
Mark, is this still something you are looking forward to do or want some feedback on?

Anyways, I'm going to share a bit of my experience working with the old and new GitHub issue templates :P
> I hope it will improve the content of bug reports but I am concerned that the added complexity of the expandable details section may actually reduce the quality of bug reports. Many bug report submitters already ignore comments.

This has definitely been a concern for many years for me and my team when working with the GitHub issue tracker. Users simply deleted the template and copy & pasted something in that nobody was able to figure out, forgot steps to reproduce or didn't even realize where to put which information. We have tried different kind of other issue trackers in the past, like YouTrack or Mantis but none were used frequent as the GitHub issue tracker, likewise because our entire development happens on GitHub.
Back in mid February this year, I joined the closed the alpha of "GitHub issue templates v2"; YAML support for issue templates alongside WYSIWYG markdown text input for the submitter (for PR templates soon).
Since early March some of my more regular used repositories were enabled for these new kinds of new templates.
The quality of our issues risen increased steadily, people now actually took the time to fill templates out properly.
According to some user feedback, the new issues are easier to use and navigate, especially for people who do not work on GitHub on a daily basis or are not as versed as others are when it comes to reporting issues.

Since mid of June, these kinds of issue templates are released to GA. I've provided an example port of the existing issues to v2, if someone wants to play around with it https://github.com/NotMyFault/jenkins-gh-issue-templates

Some references about issue forms: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by timja** [comment]
I’ve been meaning to switch to v2 templates for awhile just haven’t got around to it

**Comment by MarkEWaite** [comment]
Superseded by the v2 templates

**Pull request closed without merging**
