### PR TITLE
Shared release drafter

### PR DESCRIPTION
**Pull request by olamy**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by olamy** [comment]
plugins etc will only need to have an action doing this
```
name: Release Drafter
on:
  push:
    branches:
      - master
jobs:
   update_release_draft:
      uses: .github/.github/workflows/release-drafter.yml@master
```

this will avoid to update every repositories when an upgrade of release-drafter happen...

**Review by timja — APPROVED** [review]
pinning to @v5 also works?

What if there was a breaking change in v6, wouldn't that be quite difficult to update here?

approved anyway let's see if we get more feedback

**Comment by olamy** [comment]
> pinning to @v5 also works?

I guess yes.


> 
> What if there was a breaking change in v6, wouldn't that be quite difficult to update here?
> 
> approved anyway let's see if we get more feedback

**Review by NotMyFault — COMMENTED** [review]
If the sole purpose is to update the standalone release drafter workflow, I'm not sure if this approach is actually much useful, because to utilize it, you need to add it to your workflow(s) first.

On the other hand, the CD and repository setup promote the usage of dependabot to keep GitHub actions up to date, which already is configured in more than 100 repositories, which would take care of a major version bump on a pinned version and regular updates on an unpinned version.

**Comment by olamy** [comment]
> If the sole purpose is to update the standalone release drafter workflow, I'm not sure if this approach is actually much useful, because to utilize it, you need to add it to your workflow(s) first.
> 

the idea is to avoid receiving tons of update i.e tons of PR for all repositories to upgrade release-drafter version from 5.16 to 5.17 and have to merge every PR for single repository...
with this solution the update will happen only here as other repos use only
```
name: Release Drafter
on:
  push:
    branches:
      - master
jobs:
   update_release_draft:
      uses: .github/.github/workflows/release-drafter.yml@master
```


> On the other hand, the CD and repository setup promote the usage of dependabot to keep GitHub actions up to date, which already is configured in more than 100 repositories, which would take care of a major version bump on a pinned version and regular updates on an unpinned version.

yup that's to avoid having tons of PRs for all repositories whereas this can be updated in a single place...

**Comment by olamy** [comment]
look at last upgrade `Bump release-drafter/release-drafter from 5.17.5 to 5.17.6` this more than 60 PRs https://github.com/search?q=org%3Ajenkinsci+Bump+release-drafter%2Frelease-drafter+from+5.17.5+to+5.17.6&type=commits
maybe we could avoid all this noise and all of this redundant work with a single place to update

**Comment by NotMyFault** [comment]
> look at last upgrade `Bump release-drafter/release-drafter from 5.17.5 to 5.17.6` this more than 60 PRs https://github.com/search?q=org%3Ajenkinsci+Bump+release-drafter%2Frelease-drafter+from+5.17.5+to+5.17.6&type=commits maybe we could avoid all this noise and all of this redundant work with a single place to update

To ship it with ease, we could update the examples in this repository with your example shown.
You can also use pinned versions if you don't want to get weekly updates for xy action, though I'm also at fault here for updating to unpinned versions...

**Review by NotMyFault — APPROVED** [review]
+1

**Comment by timja** [comment]
🤷

**Comment by olamy** [comment]
grhhh I guess this doesn't work because how we use permissions here :( 
/jenkinsci/htmlpublisher-plugin/actions/runs/2055119492

**Comment by timja** [comment]
You might have to provide the github token as an input.

Do you want to revert in the meantime?

**Comment by olamy** [comment]
interesting as I use the same pattern without any issues at Apache https://github.com/apache/maven-gh-actions-shared/blob/v2/.github/workflows/release-drafter.yml

**Pull request merged**
