### PR TITLE
Jira

### PR DESCRIPTION
**Pull request by jsoref**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It is "Jira". https://community.atlassian.com/t5/Jira-questions/Is-it-quot-JIRA-quot-or-quot-Jira-quot/qaq-p/681163

**Comment by jsoref** [comment]
Sigh. 
image

There are also other files in this repository that call it JIRA.

I'm ok w/ the reverse patch for this repo, but I wouldn't make it until the above picture was fixed. Until then, my current proposed patch is more correct than a generic "some other instances no longer capitalize", because what matters is *this* instance -- which clearly is all caps,

**Comment by oleg-nenashev** [comment]
> I'm ok w/ the reverse patch for this repo, but I wouldn't make it until the above picture was fixed. Until then, my current proposed patch is more correct than a generic "some other instances no longer capitalize", because what matters is this instance -- which clearly is all caps,

Not the hill I am ready to die on TBH, it is a pretty low priority being compared to other terminology issues like "slave". If you feel strongly about the Jenkins JIRA instance name, I would suggest creating an INFRA ticket

**Comment by jsoref** [comment]
So... I think for the time being JIRA is the correct spelling for this:
image

I'm happy to make the JIRA->Jira patch once jenkins infra switches, but for the time being, I think my change proposal here is correct...

**Comment by jsoref** [comment]
https://issues.jenkins-ci.org/browse/INFRA-2532

**Comment by timja** [comment]
The infra issue is fixed now this can be closed

**Comment by jsoref** [comment]
@timja: As I said, there's a bug either way. Reversed.

**Review by timja — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks! And sorry it has taken so long

**Comment by jsoref** [comment]
Hey, spelling is hard. That's why there's https://github.com/marketplace/actions/check-spelling

**Pull request merged**
