### PR TITLE
Release Drafter: Reference all contributors in the bottom of the release draft

### PR DESCRIPTION
**Pull request by oleg-nenashev**
I am submitting it for a discussion. Not sure we want to merge it, but feedback would be appreciated

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Opinions @timja @jetersen @halkeye ?

**Comment by jetersen** [comment]
Should properly be aware of this bug: https://github.com/release-drafter/release-drafter/issues/569

**Comment by jetersen** [comment]
I recommend that everyone switches to github action and use dependabot to update their release drafter action version as well :) I know a lot of Jenkins plugins is using the GitHub app which has performance issues.

**Comment by timja** [comment]
so does the github action 😉  (because it rebuilds the image)
but I still prefer the action as at least its consistent

I kinda like skipped ones still being there tbh

**Comment by jetersen** [comment]
I still have WIP trying to split the app and action, need to finish it.

**Comment by jetersen** [comment]
This should be closed.

GitHub included contributors by default.

**Pull request closed without merging**
